version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8111:80
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/var/www/html
      - ./www/public:/usr/share/nginx/html
    links:
      - php

  php:
    build: php
    volumes:
      - ./www:/var/www/html
      - ./tensorflow/classificator/tf_files/animals:/var/www/html/all_classes
    command: >
      sh -c '
      /usr/bin/composer install --ignore-platform-reqs -vvv &&
      php-fpm
      '
    depends_on:
      - db
      - tensorflow

  tensorflow:
    image: tensorflow/tensorflow:1.12.0
    volumes:
      - ./tensorflow/scripts:/scripts
      - ./tensorflow/classificator:/classificator
      - ./www/public/test_images:/classificator/images_to_classify
    tty: true
    ports:
      - 8888:8888

  db:
    image: postgres:10
    environment:
      POSTGRES_DB: dot
      POSTGRES_USER: dot
      POSTGRES_PASSWORD: dot
    volumes:
      - ./var/db:/var/lib/postgresql/data
    ports:
      - 5434:5432